export default {
    en: {
        billingDetails: 'Billing Information',
        createdAt: 'Created at',
        customer: 'Customer',
        id: 'ID',
        nameHeading: 'Name',
        paymentMethod: 'Payment Method',
        priceHeading: 'Price',
        products: 'Products',
        quantityHeading: 'Qty.',
        shipping: 'Shipping',
        shippingCost: 'Shipping Cost',
        shippingDetails: 'Shipping Information',
        shippingMethod: 'Shipping Method',
        skuHeading: 'SKU',
        status: 'Status',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'VAT'
    },
    pt: {
        billingDetails: 'Dados de Faturação',
        createdAt: 'Criada em',
        customer: 'Cliente',
        id: 'ID',
        nameHeading: 'Nome',
        paymentMethod: 'Método de Pagamento',
        priceHeading: 'Preço',
        products: 'Produtos',
        quantityHeading: 'Qtd.',
        shipping: 'Portes',
        shippingCost: 'Custo do Envio',
        shippingDetails: 'Dados de Envio',
        shippingMethod: 'Método de Envio',
        skuHeading: 'SKU',
        status: 'Estado',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'IVA'
    },
    es: {
        billingDetails: 'Dados de Facturación',
        createdAt: 'Generado el',
        customer: 'Cliente',
        id: 'ID',
        nameHeading: 'Nombre',
        paymentMethod: 'Método de Pago',
        priceHeading: 'Precio',
        products: 'Productos',
        quantityHeading: 'Ctd.',
        shipping: 'Envío',
        shippingCost: 'Custo de Envío',
        shippingDetails: 'Datos de Envío',
        shippingMethod: 'Método de Envío',
        skuHeading: 'SKU',
        status: 'Departamento',
        subTotal: 'Sub-total',
        total: 'Total',
        vat: 'IVA'
    }
};
